import { StravaActivityRaw } from "./types";

export const all_activities: StravaActivityRaw[] = [
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 22445.6,
    moving_time: 5276,
    elapsed_time: 6280,
    total_elevation_gain: 232.1,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9978009074,
    start_date: "2023-10-04T20:01:46Z",
    start_date_local: "2023-10-04T15:01:46Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 3,
    kudos_count: 13,
    comment_count: 0,
    athlete_count: 7,
    photo_count: 0,
    map: {
      id: "a9978009074",
      summary_polyline:
        "uzweG~wo`PhD{Ct@c@lCeAr@In@|@VAvCgAxC_BpE{Cj@i@pA}ApBwD\\e@ZKjAeDrAeBnE{InByE|@sIJ_DIcBrAsBF}@hCaCjC{EZe@V@B]d@oApAuBzCeGxFoKVyAjAsCN_AtB_UGhB_AxKoAbHoAtEoKjSkHvM[h@e@Xi@t@cCrE[Ha@[g@aBo@mDu@yBmD}DaA_AeA_CDc@b@MbIAvAFTJD`CH`BHvFUr@]ZeALq@uC}BiDmBqBw@sAOq@DMzASxEE^KHq@A_AO_Bu@MmGLgAZSZn@vCL`@VLnEYlE?^NLpFCvEIt@]`@u@TYUc@wAc@_AeEoEo@_A[qBPMtGOv@QCuCU{@{AMqENgA`@Gn@`@tBNd@VRdI]dADh@RJlDCxGIp@y@r@g@ES_Au@cB{E_GaAwBBQLIr@GfGCRWBs@EgBIk@_@MuH\\y@\\GVr@`DTNbGMlCDr@NFdAGtKa@bA[Pm@GMaAc@sAqF}Gg@cAKi@BQv@OrF?b@MHi@CwBI_@e@WqFHgBVSHMZ|@zCNNhFM`EHXPBrMKr@[X_@Lc@?SgAg@mAsAqBuCkDg@oAMk@NSx@IdGALQDq@IyBISWUg@?_H^a@HONEd@p@zCNJvF[nEVDhHMpEIX[Vg@LOCSoA_@y@cGcIg@mBNMbIGNQ@WC{CIU[OaIZu@XGb@f@xBR^ZLfFSrCFv@NDrLIfAWd@m@\\_@GYkBeAqByEoF_@_AKo@XQvGDn@OHUE_DG][MeGHmB`@Mh@f@|BJRRJ`LCj@RG`NMb@y@v@_@UYsA]y@wCeDwByC[kABU^UlDPrCSL[@[UmCMO]K{HXo@ZIR@Vf@rBX`@rKE\\BVTHzDAzGOf@k@h@m@?]aBc@{@}@mAcBaBuAkBc@{@Mk@LYl@IbHELQFe@QeCI[[S_HTmAZSZj@zCVRrLE\\JAvMSz@i@Zo@GSgA]}@k@}@cEkEk@gAYcABUz@KzG@NKF_@CcCMq@MKeAGqFTeA\\OP@Xh@hCZb@`CMxCCxCRPNEdDFvCCdCIj@aAlABb@r@~C~@nAK`EkAxJuDpIu@hA{A~C{@r@oAlDaA|@kBpDm@x@kDxCeDrBmD`BwBl@o@eAa@Gm@Ro@h@yB~@oFbFgBxBcBjCq@r@c@LoBPs@bBM`@?r@Ud@iD`DtDuDNg@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.05415794253349, -89.37884540297091],
    end_latlng: [43.054450722411275, -89.37892125919461],
    average_speed: 4.254,
    max_speed: 7.264,
    average_cadence: 85.8,
    has_heartrate: true,
    average_heartrate: 143.4,
    max_heartrate: 189,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 277,
    elev_low: 258.1,
    upload_id: 10692459899,
    upload_id_str: "10692459899",
    external_id: "garmin_ping_297922033072",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 19349.4,
    moving_time: 5047,
    elapsed_time: 5390,
    total_elevation_gain: 115.3,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9971437513,
    start_date: "2023-10-03T19:56:34Z",
    start_date_local: "2023-10-03T14:56:34Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 3,
    kudos_count: 11,
    comment_count: 0,
    athlete_count: 4,
    photo_count: 0,
    map: {
      id: "a9971437513",
      summary_polyline:
        "as{eGpnv`PeBDSZA|BKnA[z@Ft@ItCMp@Y`@kB@kBOAN~@K{DKmAj@y@DqJGg@Nc@^]t@k@pCcAjDYrBBRTf@jAv@fAxAf@lALr@PfBBtBe@fDe@lBqAnBeB|AiDvDc@pA]`@w@RgB`C}C|HeAvAy@b@aGt@iBb@MOe@oASeFM_BQu@wBqEU}@UwGM}@B}CIy@mBiHy@{Aa@sAs@cAq@}AiAgEcAuBCcBWqA@[cAmAaCeAyAkAM@@ZlAlAv@lAlAp@~AdDbApAd@|@hArEBlAP`BCYP|FGhLOtDKp@Wh@QfA_@nAg@d@[j@Ed@a@f@o@fBe@d@c@L]b@WhBi@b@g@lAm@j@gARoAlBMFmA@oAbBkB~CeArAc@xC@x@Ld@nAdArAzBNh@QjCbAdGz@bCp@|C`CvEn@x@Zp@rAdFVZfAa@pAQr@Vf@nAV|@~@rKFLl@Pn@t@n@S^DjAxA^dAObA?Vj@hAThAVl@ZLd@O`AcA^KlCt@z@v@r@bA\\rA?hARbAn@pATS|JoNh@YlAUxCI~GPj@Uf@e@t@kAfAN`BIx@HPoDl@}D@iDaA_CIi@XgB_EeA]mCYq@_@uBOuBOo@_AgBMCsEpBsErAqI?wAIYWwA{BqDoKq@aCi@{EKgBuAmKCqDJs@Z]xCy@`Gy@rAe@Z_@dBqDv@sCd@_A~AqBn@Sz@cA~E@xA`@~DCJJe@fBcAbCa@tAKJm@sCJU~Dr@NC]eAK{@IG{AvEO\\MBo@{B@]ZGhCn@t@JDEs@oCaB`FO\\I@q@iCL[\\?rDv@e@cFeGDs@a@iE?i@|@m@RyA`Bw@vAmAlDaAlBo@t@iAn@qJ`B}@aDYcGQo@kBoEUmAOcBCsCQmBKaDeAgF_@iAwAwCo@sBa@y@c@qAcAuDs@kAYuCSu@qA_BeEcCQADRfC~CjAp@hA|BbBdC~A|FhA`Cn@jBl@hAn@hBlAzFj@nNP~@~BfG`@~Ht@tBnA_@|Ei@pBg@b@YfBaDxAiEd@w@rAeBv@W^c@N{@FKhGoG~AuCTm@f@_FCcBSmBaAyBw@}@wAkA[kABa@n@sBd@_AtAsF`@g@fAk@fGXfCKtAg@vDRs@LKU`BJjBAZKTi@Jq@CiANaDFs@Rk@zBV~JMjC`@fEFXYpDQPWAg@o@yC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07133405469358, -89.41088774241507],
    end_latlng: [43.07022747583687, -89.41046185791492],
    average_speed: 3.834,
    max_speed: 7.182,
    average_cadence: 82.8,
    has_heartrate: true,
    average_heartrate: 141,
    max_heartrate: 157,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 307.8,
    elev_low: 259.5,
    upload_id: 10685614842,
    upload_id_str: "10685614842",
    external_id: "garmin_ping_297752452067",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 16124.3,
    moving_time: 4002,
    elapsed_time: 4487,
    total_elevation_gain: 93.2,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9964648124,
    start_date: "2023-10-02T19:53:00Z",
    start_date_local: "2023-10-02T14:53:00Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 9,
    comment_count: 0,
    athlete_count: 7,
    photo_count: 0,
    map: {
      id: "a9964648124",
      summary_polyline:
        "wr{eGhnv`PeBDY\\AvBGh@QRKj@@lFGp@]f@wCAeAKGFHJt@K_EMk@\\_APeKAg@Lc@f@a@dAo@nCgAjDObABp@FPtB`BnArBT|@TfC@z@Ep@u@fEmAjCc@n@yBtBmCzC_@nAY\\k@JgBvBaArBm@dBiBjDaAl@cDn@{BXwA`@c@}@]yA[qGkCiGUaAO_CA}BQqBIkCo@mDk@yBo@iAkBuEc@k@_@}@_AkE_AcBE_Bc@sB_AkA}E_CCFHR|@v@tAhBh@L`@\\`BlDvA|BdAjE?x@l@hFJjEMtJM~@ChAIn@Sd@q@zC_AbBIh@k@r@Yn@Ed@UT}@Zk@lCq@d@Of@{@jAsA\\wAjBkABWHUp@[^m@nAo@t@qAzBWfBG`BFp@jAx@hAfCN|@Mn@CnAJt@d@hBDp@Zl@|@`EXn@VbAd@h@nAxCvA`ChAbFNLPE`@e@pBSp@d@\\v@RjAh@nGb@jC^DtAKl@^~AJ^NVh@d@d@pBr@Rn@AhAx@jBz@j@|@\\tAtAXj@Xr@Jr@P~Bb@~@RGlCqErEkGdAw@b@OpD[`EZfBG~@a@dAcAf@I|@F`CEX{Cl@qDF}@K}Cq@sBKg@PkATg@~@_Ax@]\\cDd@oADs@a@WG]@y@x@{Df@qEDeA\\kB?i@gCp@kAh@{AfAiDlDgC`BsAp@qE`BqDhAmAP{FHuCMYKcBaDkAqEu@aBm@yBk@yAo@gHgA}HSeC?cDVq@n@a@vBe@dFe@zAg@j@i@v@uAr@{A|@mC^w@zAqBXSb@Iv@aAxECtAXrDG\\Lj@|Bg@k@c@MqC|A_@b@Mr@B`@JXj@l@TAh@QfBeAXYNg@@s@Og@]]a@GcDnBUl@Cp@Nj@XZj@D|BkAh@a@Ne@Bi@Mm@Yc@c@QkCvAg@`@Sr@A^Pt@\\RVBb@KdCoATWHg@As@Wo@i@YuC~Aa@^Oj@@l@HZPTl@PbA_@fBgAL[Dq@Iq@_@i@i@EeDhBORGZD|@^p@RLTAxCsA\\_@Fm@Cq@So@i@YcAb@mBjAUf@Cn@D^Tf@h@Tl@OxBoAEiGjBFd@b@^@n@WlAM~JGbA[jAd@xAMrA[LYOsFqC_^y@yNNkRDQHCpA@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.071240428835154, -89.41181075759232],
    end_latlng: [43.071336233988404, -89.41185073927045],
    average_speed: 4.029,
    max_speed: 6.902,
    average_cadence: 83.7,
    has_heartrate: true,
    average_heartrate: 142,
    max_heartrate: 175,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 301,
    elev_low: 259.5,
    upload_id: 10678532364,
    upload_id_str: "10678532364",
    external_id: "garmin_ping_297577641596",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 6452.1,
    moving_time: 1715,
    elapsed_time: 1771,
    total_elevation_gain: 24.4,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9961470556,
    start_date: "2023-10-02T11:24:52Z",
    start_date_local: "2023-10-02T06:24:52Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 8,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9961470556",
      summary_polyline:
        "oyzeGlsv`Pj@D`@Cn@Fb@Xb@APXLtAbAhFRpBXxAAHDb@b@~Bt@fFZzAFr@|A|Jt@hDr@~B^~@Rj@Rd@\\j@Nd@t@~@\\~@|@z@b@P~@tAb@ZPn@lAvA^l@xAbBFL^h@VV\\t@|@jA`@\\f@n@Xj@LP`@^FPZ^n@~@Zf@BNRd@VZlAlBl@pARn@f@~@j@vA`@jAfAfBZz@t@lARr@l@jAHVfAbBV~@Z`@f@pAv@|Ab@r@jBlE\\`AP^dA~Az@xAn@z@`@n@LZX^`AdA`@l@b@^b@h@NZ\\b@~BtCPHw@o@k@m@gAqAa@a@wBmC{@w@Ye@_AaB{@uAYo@gAwBcAcBYq@u@uAg@oAm@cBc@m@[}@[e@}B_FUu@}@wAo@_Bw@aBYu@[s@{AoCaAwB[i@{@qAeBqCg@m@aAyAm@q@}@wAQU][We@c@k@GEYe@}@eAeAwAe@e@]aAm@e@a@e@a@w@c@i@cA_B]y@][C[e@y@c@}@sAcEYeBg@}BoA}HEw@[}BCk@q@oDU_AKYA}AMs@e@aBKy@Qq@ASQm@YyAKs@EKKEQF_BD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.070369213819504, -89.4145973213017],
    end_latlng: [43.07032202370465, -89.41412550397217],
    average_speed: 3.762,
    max_speed: 4.77,
    average_cadence: 82.8,
    has_heartrate: true,
    average_heartrate: 137.1,
    max_heartrate: 153,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 287.4,
    elev_low: 267.2,
    upload_id: 10675212486,
    upload_id_str: "10675212486",
    external_id: "garmin_ping_297500279389",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 25030,
    moving_time: 5659,
    elapsed_time: 5717,
    total_elevation_gain: 38.6,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9957672143,
    start_date: "2023-10-01T14:40:07Z",
    start_date_local: "2023-10-01T09:40:07Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 4,
    kudos_count: 21,
    comment_count: 0,
    athlete_count: 5,
    photo_count: 0,
    map: {
      id: "a9957672143",
      summary_polyline:
        "{m|eGn~k_Pu@U_@]_@w@Ei@OiID_CHs@LoF@wBv@gKBcBReBTkAt@cKh@sFdBsVV}BPeETeB`AuKp@eM\\gCR{B^yB\\uCv@mElAkJZ{AJy@Rw@FkA`@mBz@cGr@oDNsAh@mCFaAp@sEr@_FfAuG`@_DlAsHNeBLw@|@wERmB|@eFtAeKb@uBx@}EtBiOpBaMV_Cf@iCb@yEr@cDN{AlAgI`@eDR}@J{@n@yCfAgGLeADaA^{Bh@iE|@yE@_@d@oBD{@Js@hAyGfAuFNqAp@sDXaDLg@rAcM\\yFF[DoCL{C@oDFsA@gBF}AOcGC}CU_EGsBUsDE{A]yEUuEy@eII}AmAwKQqAs@{HUeD[kCYyDYwGHcBAc@J_B?_AJkAZmBt@cDtAyDvEmL~@oC^o@n@mBl@uANm@Zk@zA_E`AkCLo@zDeJrFaOn@sArAqD|BsFdBeFl@wBdAcH`AqMJ_@NgAf@oIpAyO|@wFf@wBlAoDfC}F`FqMnBoElB{Ej@eBfGgN~@oCdBaEfAyCPo@tA{CvBsFh@cAdAuCxI_TfCuG`AuBf@oBh@kApAwDhBwH`@iCr@yGBu@\\kD`@uJG{EBo@IoBSyDMeFWmEG{Cs@}PImAUsGEsCQwBGiD_@uFGcDe@}JIqCS{Di@gDUcCCy@g@cDMw@e@yAWuB_@{ASiAa@gAE_@{@cDU{Ae@iBcA}Ew@{Ci@sCM_AUs@WmAUq@o@mCO}@w@cCUuASs@Iu@q@mCu@gCMm@IcAQaAqAmFs@kEk@kBoA}EWeA[oBi@qBg@mCwAmFgBsIe@{AE]qAeF_AqEEc@u@oCw@aEaBwGkAwGmBoHmAyFqEwQWqAEa@YiA}AyHsBcI_AwEu@yCuAsGOu@@S^e@B]wAyFy@oDCoAHu@tBwFRiABw@C_@]oBsAmF_DeOQUw@KoGKs@SKIOYgA}Ey@yCs@_Ek@sBSkAk@qBcAqEuAkFm@sD}@kDaA}EeBoHuA}Hc@mDBo@Kw@g@uBKk@O{Be@eEg@sDGy@[{BGeAUgBWsAw@wGc@{B[gCKw@?y@OsBWyAMyAyA}KIiB@WUsCGqBHaB@{AXiHV{ALa@`AoJn@eEHaA`@uC\\qDd@_Dt@aHj@{C\\oAn@eBbDyJj@uBh@{A~@yDf@yD@s@JmAF{FAkDDiBEaBHyA@kAGsCBqHGkA@eA",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.076232858002186, -89.19752455316484],
    end_latlng: [43.06433390825987, -88.91427875496447],
    average_speed: 4.423,
    max_speed: 5.27,
    average_cadence: 84.8,
    has_heartrate: true,
    average_heartrate: 153.4,
    max_heartrate: 177,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 275.6,
    elev_low: 253.1,
    upload_id: 10671122973,
    upload_id_str: "10671122973",
    external_id: "garmin_ping_297372369172",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 11366.3,
    moving_time: 3097,
    elapsed_time: 3111,
    total_elevation_gain: 34.5,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9948926376,
    start_date: "2023-09-30T11:55:47Z",
    start_date_local: "2023-09-30T06:55:47Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 9,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9948926376",
      summary_polyline:
        "ygzeGpcv`PhAyAF_@@OEyA@_BGwAJe@DEb@Ol@ErAJr@C|AMhA@VCLG\\@VFj@@rBC@CGy@C}@?yDC]@[IeF@{AF_BGkBB}B?cABw@Gq@@qCG_DTy@E_ADe@DgBFq@ZU`@IfA@~AEx@DzCI\\Db@IbBgAjA_ArBuAhCuBl@cAPi@Jy@B}@Ks@McCSaC?m@@{@\\kBBYHwEBU@s@EcA@m@Cq@?uGBo@@eAHg@\\Sp@B~@?NQCk@BwBG_CJ{EAuADkFCaFBsBA_ADm@Rs@HK\\[~AgAjB_Bj@[NQT_@`AcALe@Ie@Ym@AOIUIMKESDa@^o@T[f@e@^WJ[Bi@Ci@PY^Ul@Qj@AdAWh@sAjAiAjAoAz@q@p@c@Zk@Zs@jAmBxAgB~AeBnBs@p@uAz@{AnAkAn@w@\\y@Ps@Hw@@_AEuCg@s@QcAOwCU]Ge@Mi@We@Qs@OmAe@sAu@ENEt@P\\HTM~@Dt@P`AX`Ab@`Ah@~@hAvA|@\\tBdAfAz@j@x@`@|@RbAFp@At@UrBDd@Z\\`@Xx@lAJn@Id@Y|@s@~As@tB_@jBQlD@hCHrA\\bAj@t@fA~@^Rd@LJFN^@p@ClCD`AFr@NTZR^X~ABXXDd@CvB?DOICDLdC?fABTANH`G@d@I~A@`EHlD?bFEbBDnCEjDENKHc@@sAG}AHqFGyAJw@GUFE^Cv@BpCAxASr@Yh@m@t@wB|C_AlA_@l@k@j@u@hAKHm@VKZ^rAh@~Cf@xB^hBNtBJHHt@d@pCRxAb@xBr@dFJvAf@nDPl@L|@l@lBVfAj@xAXf@Zt@^h@j@hAd@l@jBrCdAdA\\z@PX^b@l@~@pA`BXb@RTJFyAiC[_@U_@[_@mAgAa@w@s@e@iB_Cy@_B}@qAUq@E]]m@Qi@{@oBi@mBc@kBOsAM}A[iBMmAKo@EEK[Mw@Qo@W}A]{AAYMw@WmCEo@SkAMoAQu@Eu@Ko@a@}@YoAS?STQMa@K",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.06664127856493, -89.41246714442968],
    end_latlng: [43.07018514722586, -89.41397471353412],
    average_speed: 3.67,
    max_speed: 4.456,
    average_cadence: 82.5,
    has_heartrate: true,
    average_heartrate: 146.2,
    max_heartrate: 172,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 276.3,
    elev_low: 258.6,
    upload_id: 10661955145,
    upload_id_str: "10661955145",
    external_id: "garmin_ping_297169450496",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Evening Run",
    distance: 6525.1,
    moving_time: 1752,
    elapsed_time: 1773,
    total_elevation_gain: 25.8,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9945777702,
    start_date: "2023-09-29T23:08:23Z",
    start_date_local: "2023-09-29T18:08:23Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 8,
    comment_count: 0,
    athlete_count: 5,
    photo_count: 0,
    map: {
      id: "a9945777702",
      summary_polyline:
        "iwzeGnhv`PHHZrBTbAFp@P|@XZJF\\ZHb@NdBJl@Tr@Hp@?RFf@A^@jAVdBFVLn@Pj@Fv@Pb@Lx@Pn@`@xCNj@JdAN~@AFLh@Dj@Jx@Nl@L`Af@pB^fAJj@`@t@^|@LPZ`A`@n@EJd@z@h@h@Rf@Pl@~AvAXj@Z\\j@vAdA|@h@|@p@x@RBNJ@HTh@`A|@^p@^\\b@t@z@bAXd@j@vA|AfBPb@jAlBhAhCRr@lA`CbAbCt@|Av@~@hB`E`@h@\\|@t@|A^bAn@rAf@tAt@bBPVXp@f@t@j@tAR^`@h@n@jA\\b@d@\\Pf@^f@Zd@Z^Zn@f@l@HVWUg@k@a@]cA_B_@_@i@kA_@[OUw@_B[_@gAaCWq@Wg@QQ}@gBGUa@m@q@}AGWm@uAaAoBi@yA_@u@i@qAUe@_@]Su@yAaD]q@Um@}AyBo@}AaAeBWq@q@u@]s@m@y@Yk@e@u@a@]k@y@i@g@Sa@cCqCIWqAeBw@u@g@eAOSWQe@s@Y]uB}CWc@o@w@i@cASi@CQ]y@Us@Um@u@mDSgBg@kB]sBKmAE_AIs@Qs@_@{BS{BMm@Ys@]kBOa@Ei@a@oCAw@Cq@McAk@iCCw@EW?OmA{BQu@c@cAYi@e@q@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07038807310164, -89.41027896478772],
    end_latlng: [43.071001544594765, -89.41040519624949],
    average_speed: 3.724,
    max_speed: 4.777,
    average_cadence: 82.1,
    has_heartrate: true,
    average_heartrate: 135.2,
    max_heartrate: 147,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 286.5,
    elev_low: 263.1,
    upload_id: 10658666721,
    upload_id_str: "10658666721",
    external_id: "garmin_ping_297084081899",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Loyola Track Meet",
    distance: 8000,
    moving_time: 1467,
    elapsed_time: 1467,
    total_elevation_gain: 0,
    type: "Run",
    sport_type: "Run",
    workout_type: 1,
    id: 9944862693,
    start_date: "2023-09-29T18:46:07Z",
    start_date_local: "2023-09-29T13:46:07Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 25,
    comment_count: 3,
    athlete_count: 1,
    photo_count: 0,
    map: { id: "a9944862693", summary_polyline: "", resource_state: 2 },
    trainer: false,
    commute: false,
    manual: true,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [],
    end_latlng: [],
    average_speed: 5.453,
    max_speed: 0,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    upload_id: null,
    external_id: null,
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 4915.5,
    moving_time: 1451,
    elapsed_time: 1760,
    total_elevation_gain: 2.5,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9944708922,
    start_date: "2023-09-29T18:01:50Z",
    start_date_local: "2023-09-29T13:01:50Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 4,
    kudos_count: 8,
    comment_count: 0,
    athlete_count: 6,
    photo_count: 0,
    map: {
      id: "a9944708922",
      summary_polyline:
        "ib`_Glz{uOtCkAt@a@jDsBl@e@bA_ApByAnGuFnAqAtCmD|AcBb@[Z?DBVb@Dp@M`@e@d@cAV[N_@`@Sn@G^?t@YvBQ\\g@Bm@VeAFk@Nk@h@i@n@IFk@VsAb@_@NgAn@O`@e@lBi@hDSbAu@|BGHq@?_@Xa@@s@OsBIs@]e@Hc@Ve@G]RmALg@Js@D{@Hi@Ji@Fc@Ai@D}ACe@JkExAmAXu@Xi@Hi@VgGdAoHz@g@Do@LuAHeCXgHg@m@A_@N{@dA]VWLa@Nw@Nc@D{@SKEEI\\Lh@Jh@CbASj@S^WpAsANGp@@h@FxCVn@JbABjB]xI_A|BYlAQ|Cq@h@EFCBMlCo@zAa@nC_A",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [41.95104818791151, -87.64034405350685],
    end_latlng: [41.951127564534545, -87.64042904600501],
    average_speed: 3.388,
    max_speed: 4.241,
    average_cadence: 82.5,
    has_heartrate: true,
    average_heartrate: 151.1,
    max_heartrate: 173,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 180,
    elev_low: 177.4,
    upload_id: 10657551575,
    upload_id_str: "10657551575",
    external_id: "garmin_ping_297051116338",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Lunch Run",
    distance: 4515.6,
    moving_time: 1198,
    elapsed_time: 1202,
    total_elevation_gain: 3.1,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9944043302,
    start_date: "2023-09-29T16:07:15Z",
    start_date_local: "2023-09-29T11:07:15Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 4,
    kudos_count: 5,
    comment_count: 0,
    athlete_count: 8,
    photo_count: 0,
    map: {
      id: "a9944043302",
      summary_polyline:
        "yw`_Gle|uOgA`@QLw@ZcAZiATuAd@SLiARu@RqB^yC^aD\\uCToAPc@JS@u@A}De@oBIg@P_AlAm@b@m@PcANSAUEiAc@e@Mg@Fm@f@e@EEMAmAWwAUq@Wc@_@e@y@k@m@Ue@Im@Ce@Fo@Rm@Xa@`@Y`@]z@Qj@Id@Gl@Ep@CvABtBN~@TpCGlA_@hBObAN~EOgFHw@f@_C?w@SsC?_@Vo@?e@Co@@aBHmAHk@Pm@x@_Bf@[d@Op@Ch@Ft@RRL^Xp@t@f@|@Tn@N|@B|@C~CPf@`@Lf@F\\Mn@MXQt@eBXk@h@s@fASZK`@U~@aA^]LGf@AjEd@|AJh@Ep@MbAKxDWnDe@zAOXIxB_@bBWd@Op@[dEkA~Ag@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [41.95110057480633, -87.64057162217796],
    end_latlng: [41.951235607266426, -87.64022125862539],
    average_speed: 3.769,
    max_speed: 4.316,
    average_cadence: 83.5,
    has_heartrate: true,
    average_heartrate: 142.6,
    max_heartrate: 161,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 182,
    elev_low: 178.6,
    upload_id: 10656861319,
    upload_id_str: "10656861319",
    external_id: "garmin_ping_297036058409",
    from_accepted_tag: false,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 3247.5,
    moving_time: 883,
    elapsed_time: 955,
    total_elevation_gain: 0,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9942697936,
    start_date: "2023-09-29T12:02:18Z",
    start_date_local: "2023-09-29T07:02:18Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 8,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9942697936",
      summary_polyline:
        "ej__Gnu|uOOsBDo@Mw@Aa@STk@Vk@h@SCuChBsAp@QI[DYAKLIBMBUA_@V_@P{@v@_@GI@MDE^a@DWHKPUPIHe@Po@d@a@Zw@v@u@^o@j@g@LyB|@_@?I@OEiBOk@Ds@Xe@LSLOA@CP[d@Ml@Bh@Gr@QPD^?d@Cx@S^?@BJA`@Qb@Mn@[t@e@~Aw@`Aa@PEb@c@^Y|Ac@n@W^Wd@]d@g@^U|@]XSbFwBb@W\\Ih@Ud@MXELb@DZ@~APnB@`@Jn@Hx@DdAH`@Dx@Jf@Hn@Bv@Dh@YXe@Ze@`@_@XMD_@Zw@x@g@F{@^q@j@k@DaA\\c@Va@Ni@h@CJ@FV]tAu@zAeAxBgAl@SPK",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [41.944348365068436, -87.64526003971696],
    end_latlng: [41.944666961207986, -87.6455960702151],
    average_speed: 3.678,
    max_speed: 6.642,
    average_cadence: 82.6,
    has_heartrate: true,
    average_heartrate: 133.1,
    max_heartrate: 145,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 182.4,
    elev_low: 180.8,
    upload_id: 10655454935,
    upload_id_str: "10655454935",
    external_id: "garmin_ping_297004837504",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 9535.7,
    moving_time: 2532,
    elapsed_time: 3512,
    total_elevation_gain: 8.6,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9940105265,
    start_date: "2023-09-28T22:13:03Z",
    start_date_local: "2023-09-28T17:13:03Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 6,
    comment_count: 0,
    athlete_count: 8,
    photo_count: 0,
    map: {
      id: "a9940105265",
      summary_polyline:
        "_ba_Gxm|uO_@Fg@By@AkA@YBQDe@RWn@O|@Oh@_@jAKNq@d@g@X_@?_@[Wc@i@gAc@eACG_@MeAh@q@Rq@KsCi@eAl@a@Lo@As@EKFMZCFB`@JZBPPr@DDPFxADv@GbDR~AC`@BLDV^n@lBTvAZ^^O\\YNSPg@^wBV{@^k@fBmB^URCTRb@~@dAzAZRXIlCsBZa@v@cBZe@h@Wb@E\\U^g@RKfA[r@OZWE_@G_@?q@Jk@V_Ap@eAd@W|Ag@~BcA|GeCvCyAhEmCpBwA~BqBRWbAcAjCgCtCiD`@]dBwBb@YD?RRDRMb@U^o@h@}@h@IHQ^Ib@E^Br@ATGFWHw@`A_@^q@\\gA\\a@\\o@t@q@^e@RgAZc@Ro@\\MPYPc@?gAXsAbAwA|@uCjA_CdAkAb@sAb@}@^_DbAiBt@gDhAeBr@wCt@iBn@iCf@mG~@sE`@eCPu@Ng@DaAAyCSOCgAGc@Gg@Dq@~@ONg@`@KDe@Ns@JQFg@hAb@w@XU^Cr@MJEb@Y^_@l@s@ZO\\ChALlADlALvAFd@Eb@IfFc@`@KlAMd@ClBYrAKt@MdBa@~@On@_@xAc@~A_@z@[dBi@t@]`@JfBlA_IjB}@ZyC|@_ALwB@y@HWDIDMRM`@Kp@Mn@e@nAc@d@o@Za@NKA[S[k@{@mBYg@EESGuAl@_@Li@CuBc@c@GI?I@oAr@SBeACYBOJIRAN@LLl@Tx@BBRHt@DjBAdBL|BEb@@XDTXRj@Tv@f@zBNLF?RGb@_@Rc@To@^gBLc@Ta@bByBZSd@OXHd@dAf@z@VX`@XVI`AaAn@c@\\_@pAeC`@uAAq@QGI?mB\\{BVqAEe@@}@HtBOv@Bp@EZE",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [41.95276044309139, -87.64112692326307],
    end_latlng: [41.95281115360558, -87.64097437262535],
    average_speed: 3.766,
    max_speed: 7.492,
    average_cadence: 82.9,
    has_heartrate: true,
    average_heartrate: 146.6,
    max_heartrate: 170,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 181.3,
    elev_low: 177.7,
    upload_id: 10652749170,
    upload_id_str: "10652749170",
    external_id: "garmin_ping_296922974107",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 17788,
    moving_time: 4621,
    elapsed_time: 4699,
    total_elevation_gain: 75.7,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9931211760,
    start_date: "2023-09-27T14:00:51Z",
    start_date_local: "2023-09-27T09:00:51Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 3,
    kudos_count: 13,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9931211760",
      summary_polyline:
        "}a{eGtuu`PtEAnBFbAEn@FhDErDFpBC~CUpAN|@HpCCPDv@IhABh@IvA~@Xh@Hr@z@lADd@QlBn@x@HLDj@L`@`@Zj@|AX^Nj@@n@LTzAGp@N|BdA\\Ej@gAR_ADeAIiCDwAHo@`@{@Jg@TuBBk@u@oGIcCBw@l@mDJy@pA_DdBuF^i@VSvArAVb@f@hB@l@Gp@@vAMhBBdAGnBLvABbBXz@\\^n@d@bA`@n@b@l@Tf@DbDSbCY|@@z@NfA^jDxChBjAzCvA`@b@JTNz@B|DAhBBVa@xLHr@n@jCRj@NnCHn@l@jBb@lCIfADv@Av@`@jDPr@n@zA`@XnBEz@I~DmAjABl@Pd@~@HZBh@@`CIr@?bCV|AWvFKn@MzBQ|AHv@BfAHZz@|BbBvD^~AP^Fv@n@rBt@`BhCxEfAhA|BtA|@Xh@BzDEjEs@|@BrATx@h@n@t@V|@h@fCVdDJlEUvEk@nDs@bBUr@a@z@_AlAKd@GdF?xDBtBQ|F@ZVb@`@@t@YbAyA\\Wb@GlAb@Tl@EzB@`CQtFHnAGdBBzDEbCJbEWjBWdA}@bB]`@iAUCPGp@EdDArGDlDEjJBv@AZMp@i@jBqA|D_@p@a@HgG_Ak@CiDuAkCeBsByB_B_Cw@aB}AcEsCwIeA{DYy@g@}@YgBqAmEwBgG}@{Bm@_AkAcCOg@q@oA_EkGwAaBsCqDa@o@}@k@[]i@eAiCcDa@_@{AqBwBgCeBkCu@u@oAgBu@{AaA}A_C{EQg@wAuCa@k@Qo@uDgIuA{BWi@Ss@mAoCiAaCMKq@}AeBkDwA_CkAwA{@qAm@o@{EcHyCiDa@eAmAiAe@y@gByBm@eBqAoCmAyDc@y@_@aBKoBKs@]gAa@}CKcBiByKOc@MqAgAuFKiAg@yCYcAKkAk@uA?eAKu@m@oDMi@g@cDs@sDMw@?}@[aCuAsI[eCWeAOmAg@eCIiAYcBKsCBkATgCbCuJl@eDt@_Dp@{DJgANaAfAaE`AkEzAaFp@eB~@mBfAaB@s@Bb@Mj@oBbDkAlDYjAg@jAkAvFk@bDUdBk@xBmAbGy@xCsAvFaA~EGbB@x@RdC`@|BH|@ZvBHtALr@`@pAdCbP?ZQX[BmDKk@Li@@o@KsAHc@TGV?fB",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07036032900214, -89.41059311851859],
    end_latlng: [43.0712846852839, -89.41161814145744],
    average_speed: 3.849,
    max_speed: 5.464,
    average_cadence: 82.2,
    has_heartrate: true,
    average_heartrate: 150.7,
    max_heartrate: 178,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 308.9,
    elev_low: 259.1,
    upload_id: 10643498447,
    upload_id_str: "10643498447",
    external_id: "garmin_ping_296703166495",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 17747.2,
    moving_time: 4091,
    elapsed_time: 5851,
    total_elevation_gain: 139.9,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9926938648,
    start_date: "2023-09-26T20:11:46Z",
    start_date_local: "2023-09-26T15:11:46Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 15,
    comment_count: 0,
    athlete_count: 7,
    photo_count: 0,
    map: {
      id: "a9926938648",
      summary_polyline:
        "}qqeGn{paPdIyJxEwGz@wAtBmCl@_@ZGpAFr@d@Vp@Fz@KrGQp@wAvDq@z@{BvBq@z@Wr@@jHIpCu@nE_@jAc@|@c@^yAVqA`@{CBkA]gA_Ay@kAaAiEAi@XO`@HtBjAjAfAlChB\\Hf@Ez@W\\]fAkC|@cD`@cCBs@E}Fl@eBAm@Mi@e@a@_@GgAt@cDlEgFlI{@dAsAdA_@Ne@Ea@a@g@uAa@oB@y@ReBTeAf@_BpA_DzAwCx@u@`@W^ZZt@Fj@O^oF`HSl@c@rB_@`Eb@cBpEqFvJeMjE{GfBaCt@a@pABv@X\\d@NjAMjGy@tCg@dAsDfEaA~AGjA@~GG`Bu@nEa@vAg@`Am@ZaG`@wBY}@i@}@_A_@kAwAoGBu@\\iAfMaQ|HsLlBmCr@i@RCnAHl@R\\`@Rv@OjHcAhD_@p@{CbDcAzAO`@IdCAdFQvBg@pCq@dCe@t@UPq@N~@Y^a@Le@}@qAKi@jByFNw@CY_BoBk@vB}@zBo@|A]\\Q?a@WYy@Es@Lq@Zg@~JqMJ_@G{@y@y@e@?{@p@uC`ESf@tCvDP@wBjGq@xAc@Hc@YYy@Cs@Hc@h@y@xJqMHo@Cg@KSq@e@SC_Ab@m@r@kCdEDPV`@~AlBj@^u@bCgBlEMPa@LQI[i@QkAJq@~KcOFq@Ec@ISq@g@[CYLoAnAyBhDMXlCbD\\Rw@dCoAfD]p@c@Nc@QQ_@Q}@Ds@z@}AfJqLJa@Co@Oa@g@_@]ESFaAz@wCnECTdDvDq@tBiAtCg@lAURg@G[g@O_ABq@^w@dKaNHo@Ee@c@k@m@Sc@NkAvA_CrDAL`DxDcAbDaB|Dg@FYU[{@?cARm@z@oAnI}KJk@Ky@m@k@OGe@H}A`BiA|A}GtKk@t@}AjAc@Jk@QMMKe@Q_DfIaJ|ImLp@q@jAYdAExALn@ZbBfBTj@En@_@bAm@dAcDhDi@x@Qn@GnB?xGo@jF[pAu@`Bs@ZsB\\kCJq@GmAc@c@Um@i@kAqBYkASqBHKRGd@L|BlAjDpCn@\\t@Dd@Mh@_@f@}@r@kBl@uBb@_CF{AIsEB[Ni@^q@?m@Oo@_@]e@Mg@PmAvAoFpI",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.022366389632225, -89.54949927516282],
    end_latlng: [43.02214586175978, -89.549526181072],
    average_speed: 4.338,
    max_speed: 7.322,
    average_cadence: 86.4,
    has_heartrate: true,
    average_heartrate: 150.6,
    max_heartrate: 181,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 343.5,
    elev_low: 320.2,
    upload_id: 10638987147,
    upload_id_str: "10638987147",
    external_id: "garmin_ping_296586308024",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 12889.8,
    moving_time: 3288,
    elapsed_time: 3720,
    total_elevation_gain: 49.4,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9920039801,
    start_date: "2023-09-25T19:48:13Z",
    start_date_local: "2023-09-25T14:48:13Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 9,
    comment_count: 0,
    athlete_count: 3,
    photo_count: 0,
    map: {
      id: "a9920039801",
      summary_polyline:
        "qq{eG|nv`PyB?]NOZ?tA@b@QnAKxDWh@A^Id@a@f@kCC}@IKHBHz@MuBOy@@e@Pg@XQDwKKm@L_@\\[p@k@nCe@~AWr@Qn@UhBHj@Z`@zAlA|@tA^tAPpBDpAAZIjAWxBUx@Yl@oAfB{BzBgApAaA|@Sb@E`@[h@_A\\sA`Bg@v@i@vB_@|@aAlBo@~@WTc@VmHz@eAXK?SY_@kAKu@I{@QaDK_ASk@_@q@y@yBSs@Q{@UiC@w@GiBBmBGy@Kq@Uu@QiAyAmEaAeBi@iBs@uA]eAa@oBMi@_AyAIg@?a@KiASu@DKm@y@i@g@eAi@s@g@w@][WIAGHDRj@b@VZ^f@`@r@f@\\v@\\f@xAnB~CVd@hAtEZp@v@tA^lA~A~CPr@f@vARjAXbAHv@HpBJdBDzEJv@`@tAj@fAn@nBLl@B\\TlFLn@Ph@T`@BVFDLAd@Kb@U|Fy@t@W|@w@zA}Cl@mB^_Af@aAtAeB~@]d@s@XGzBJnAIz@VjCApAFBjGVULULk@?]E]Se@QQQMWD{CnBOZGl@Dh@L^FHb@RPATIdC_BPSHYB_@C_@Qi@QUWIW@yCjBSXELCZDn@Rh@FHb@Jb@KlBiAd@c@JWD]?MG]Qc@QQa@Ia@JsBlAUPWf@@`@Lt@\\d@b@Dd@QbBaA`@]NYD[C{@EMQUUMWCSDwBhAa@ZSj@Ap@Ll@d@b@b@?nC}AVa@H]B_@Gi@OWUOWEWBwBfAi@^M\\Ef@Nx@\\b@b@Fv@]xAy@VULWF_@?a@G_@O[KGWOWAWDSL_CzAOZKv@nFkGfBJPDLXNRH@bAe@tDSrEGhD@|AEh@BfAATDTK]qDCu@Bu@Me@IiAWuBQaCWuEGiAIi@EkAc@sEa@eGS_BCkBJgD?iCCw@I_A@s@DOFq@@{@NyAZOfCA\\S@{AEk@Ng@DCPEhBBf@CNIJ]Q}DBu@DEJ[K_@V}ABiAHW`BOdAC`@PTXd@v@n@nAjBhElBlDf@lAJh@H`Ab@nCAn@IHKBaEGsAFa@Nm@Bo@PmAAyAOeD?y@KuA@qBRUAe@QGMAQ@s@DWFsAA_@D{AAYFyEFs@r@oCn@sCL_@LEp@Cb@D`A@dAIh@Ad@JBD?b@ElAYvA",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07137814350426, -89.4107842259109],
    end_latlng: [43.07129776105285, -89.41179550252855],
    average_speed: 3.92,
    max_speed: 7.216,
    average_cadence: 83.3,
    has_heartrate: true,
    average_heartrate: 141.3,
    max_heartrate: 171,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 275,
    elev_low: 259.4,
    upload_id: 10631755922,
    upload_id_str: "10631755922",
    external_id: "garmin_ping_296410858139",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 21036.9,
    moving_time: 5032,
    elapsed_time: 5112,
    total_elevation_gain: 23.8,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9912801425,
    start_date: "2023-09-24T14:31:47Z",
    start_date_local: "2023-09-24T09:31:47Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 7,
    kudos_count: 17,
    comment_count: 0,
    athlete_count: 11,
    photo_count: 0,
    map: {
      id: "a9912801425",
      summary_polyline:
        "_}neG~rubP@yEIeBDoDAiCFkA?i@D_@?WNaAFo@@oBAs@Iy@CyCOw@EOe@_@O[e@i@Ua@oAeAuB{AyAoA}@{AmAgB[Ym@w@g@eASY_A_Ay@k@Qa@U]oAeAgAgBi@iCKy@Qu@UqBa@iCk@yE]yAm@uDa@eD]aEg@uBSiBQk@Ks@So@Ii@_@cAcA{DWcBo@wBWgBKsBg@uEMoBQoBD{CJaBBeBPcAHcA^gBRoB^aBHq@t@gDRiB\\eBJ}@R_EMsD@s@ASFcAKi@?_BC[?oAGwA?y@k@oH@cACm@Pi@M}BOqB_@yBeBcFy@yDW_BKeCFuAKs@Dw@@qACeCWsCGsAQuBCeA]gBg@gBUkBSy@c@uA}@oBi@iB}DkLA[{@kBe@qBy@qB_BiGo@iB[o@o@eB_@eB_@eAe@kBkAuCk@uBa@cAg@gBIQYuA[kAu@yAq@eCcAcDw@{Bc@cBu@eBSiAw@mBSo@?Oc@kAwBcHeB_FwA}EuAsDiBwFYgAsB}Fo@}ByAkE]mAc@eC]_BGcAEeBBoBD_@HsCPaAj@iC`A_DHi@bAsDJo@Z_AJ{@Zy@d@iB|@mEd@qDM}DFuBImA@{@GoAJwDQcCDmFGyG@mCEgABsBEqJDwBC}@BsAT_EXkC`CqO\\_Bj@mElA_H^wCl@_Dn@aELs@LcAn@cDl@eE\\iBNmAd@uCT_Ch@qBh@cCpCkJ`AaChB}EdAiDlBmF|@_DxAuDt@cCx@yBr@}Bf@sAt@eBlBeD`AmAn@aAlDeFt@aArGaJvA_CfCsDxC{ExEsGnAwBvC}D`@o@\\a@zBgD|B}C`@w@xCeE~BqDrDgFl@w@~BsDhIiLbBkCjBcCbCuDlHiKvNcT`GoI~BqDv@cApGmJjCoD|IwMxKoObGwItBeDvBuCpDwFbFiH~@}A|EiHpD_F`ImL`@s@nBoCt@{A\\}@h@kBTiANsANgDLiA?q@O}DKo@CoA_BsH]oAq@kDk@uDiBiIo@cESkCBaBa@eEOcAOmDK{@GeAOgA?oAMqCKq@@u@GkBSuCO}@A_AQ_CMaA@KMu@}@}C]{AiA}C[m@y@}A}A_Cq@uA_C{D]q@g@s@c@cAw@mAOa@iAgB}AsCsAuBm@kAaBsCgBqCuAyCc@wA]gBu@_DK}@Kg@MsACkBQyDKq@CeBIs@QmEYsD?e@FHLbARfD",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.00752706825733, -89.737982545048],
    end_latlng: [42.990876249969006, -89.52557925134897],
    average_speed: 4.181,
    max_speed: 5.7,
    average_cadence: 83.5,
    has_heartrate: true,
    average_heartrate: 143.4,
    max_heartrate: 174,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 376.3,
    elev_low: 282.5,
    upload_id: 10624139161,
    upload_id_str: "10624139161",
    external_id: "garmin_ping_296209065615",
    from_accepted_tag: false,
    pr_count: 7,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 9665.9,
    moving_time: 2491,
    elapsed_time: 2518,
    total_elevation_gain: 28.1,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9905996081,
    start_date: "2023-09-23T15:37:15Z",
    start_date_local: "2023-09-23T10:37:15Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 1,
    kudos_count: 8,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9905996081",
      summary_polyline:
        "ue{eGjuu`PVBn@JXIr@?hCIx@DrBEvA?PDlAChB@pCLr@Ct@Ih@Ap@Fj@ALCtCF|DKpDC\\Jb@^h@V|@`AX^@H?p@YfB?TFp@Zr@LRRj@BPn@n@XdA^p@Nl@@p@JND@z@SR?j@LpCfALEVYTg@JWLu@As@IeAEu@D_D^yCRq@Vi@@IIaB]oCOwBDgBPuAj@oCdAqCLq@r@kBj@gBd@u@\\[p@cAZ_@ZW`@e@fA_BxCiCZOzAi@l@_@v@WxHgAhBUv@AtAW`@Ev@O`@_@Xo@HG`@NfCrBnA|@fBpAv@d@vF`Ex@d@hBtAzA~@DFf@Rz@TfAb@L@ZRBdHAhBFt@MxCCnA@dCMrO@`FA`DE~CAvEIzBMR_Ar@URMBOCeAcA[D]TsAfAw@`@w@n@e@V[JQP_@f@i@`Aa@^IN_@ZMD[Oa@_@qAcBk@c@Wa@Qk@[a@_@iAMyFDeCCO?}BFcADaDAw@Ks@[c@o@i@QUgBm@}Ay@k@m@YQwAiAo@_@u@Y[EqBNu@CgBNg@A{@F]Aw@Sc@Ws@k@o@]g@Ua@WQe@Ks@OwABgB?m@Ec@Co@?_A@eAHeDC{@Qi@We@c@a@]a@II[PYf@k@`Bo@pBKv@aAbCSp@g@tCEfAHxBF`AZzBFv@@jAWlBGhAYbAOr@EXAv@@pDMt@O^c@x@ONSEwAu@s@USEg@E_@@g@CIYC}@M]Wc@Uk@Yk@]c@CGEc@W]e@mAMyBOk@Yc@K}@]k@g@g@a@?_@EqAHe@Ca@Bi@AmFDi@CUBu@Ci@@qAG{@Fe@C_@Gc@?_ADqA@eABaAEm@@mB?cAB",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.071441259235144, -89.410554561764],
    end_latlng: [43.07117613963783, -89.40918562933803],
    average_speed: 3.88,
    max_speed: 5.952,
    average_cadence: 82.5,
    has_heartrate: true,
    average_heartrate: 139.4,
    max_heartrate: 150,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 267.9,
    elev_low: 258.8,
    upload_id: 10616975756,
    upload_id_str: "10616975756",
    external_id: "garmin_ping_296047235846",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 9715.2,
    moving_time: 2571,
    elapsed_time: 3381,
    total_elevation_gain: 16.6,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9901046771,
    start_date: "2023-09-22T21:31:59Z",
    start_date_local: "2023-09-22T16:31:59Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 6,
    kudos_count: 14,
    comment_count: 0,
    athlete_count: 4,
    photo_count: 0,
    map: {
      id: "a9901046771",
      summary_polyline:
        "ox|eGfcy`PAw@Rk@PWHGjB}@^Mh@@`@LTb@Dx@Mt@y@{BLp@Lb@@`@UVqAt@_@RK@ECk@eBCM?YTShBaAd@GBBXlAJl@?HCD]Xq@^s@^]HCCk@eC@MDGpC{ATABBf@hC?FOTq@d@w@\\a@RI?M[Oq@Uu@COFOxBkAn@QBBJ\\Jt@Nj@?NELKFaCtAYBCEg@sBE]JOxA{@j@W`@CJV\\pBCDQNeCzAK@GGo@cCDUDC`CoAHEZCDBH\\ZfBELe@ZcB`AWFGIUaAW{@BWh@[fB}@`@EFZHn@R|@ADCFYRsA|@o@ZEA]eAOo@Ai@tCaBVELTHj@Nr@@^CFYRsAr@WL]HIGAG]sAGm@@EJIhBcAb@SPANXHn@Pv@AVu@h@wAv@[Bi@}BA_@BEzC}AJABBDLGDi@Dc@TsAz@EHAL^`BNTD?\\QxBwADKCUc@aBSGgC|AMPD\\VdAL\\D?ZO|ByAASg@iBOEe@V_@Xw@`@URALVdATl@NBd@Wd@gBZaBGcBc@@g@AU@aACq@@SP?DGrJClAAnCBb@IVJdAAlADxDDNFBPKRm@b@_AXc@l@w@|@k@b@UhAc@@EOuC?uBBk@NaAl@_BRw@F_@@u@A_@EYSe@C]BWd@i@Dg@By@F_DBsGFyAGgCC}AB_DEgB?s@H_B@wGBmBBs@DK\\MnBQp@Wf@Kh@EJAp@Dd@Db@J?DMDa@HOACC?KNEdCLt@CD?XQNe@?wDFw@?{AGc@VFTKEq@Fw@Po@TAn@D",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07749190367758, -89.4265435449779],
    end_latlng: [43.071461794897914, -89.41192827187479],
    average_speed: 3.779,
    max_speed: 6.633,
    average_cadence: 83.6,
    has_heartrate: true,
    average_heartrate: 138.6,
    max_heartrate: 171,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 274.9,
    elev_low: 260,
    upload_id: 10611765949,
    upload_id_str: "10611765949",
    external_id: "garmin_ping_295926135288",
    from_accepted_tag: false,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 4913.6,
    moving_time: 1274,
    elapsed_time: 1283,
    total_elevation_gain: 12.7,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9901045585,
    start_date: "2023-09-22T20:48:04Z",
    start_date_local: "2023-09-22T15:48:04Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 9,
    comment_count: 0,
    athlete_count: 8,
    photo_count: 0,
    map: {
      id: "a9901045585",
      summary_polyline:
        "au{eGhnv`P[GQp@ApCIrBAbB]pACt@]f@GDi@HwBEa@IY@CLD@\\CZI{@IiAEo@Ho@Xa@LOBc@?m@GEBKPBbDElBBtBEv@Wv@?F@jEBr@EpEF`AAv@KzB?tDEvAKpB?p@CZKj@a@Vk@Ps@d@]HOIYEqBBc@Cy@Bc@Oi@GwAAoAB_@L]h@UNg@N{AzB]r@Y`Au@nBwAnCGJ_@Xe@Vo@NkD`@o@@i@Je@Vw@Hc@NKHWb@Qt@V`Dd@nDHZ\\fDh@pEN~@Ft@Ll@jChIpAtDJPh@p@f@Lb@Xf@LLBv@@dBCv@EL@f@Av@KJ?vCe@`A_@^]OqAG}D?}@HaE@oAEaBHgDAi@KoAEw@NyADy@@wELyDPk@?cDCi@B{@@_CDiDDs@HMZG",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07156866416335, -89.41115294583142],
    end_latlng: [43.077516378834844, -89.42516656592488],
    average_speed: 3.857,
    max_speed: 4.658,
    average_cadence: 83.4,
    has_heartrate: true,
    average_heartrate: 136,
    max_heartrate: 149,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 274.8,
    elev_low: 259.4,
    upload_id: 10611764750,
    upload_id_str: "10611764750",
    external_id: "garmin_ping_295926094222",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 14805.3,
    moving_time: 3982,
    elapsed_time: 4601,
    total_elevation_gain: 94.2,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9895119643,
    start_date: "2023-09-21T19:48:46Z",
    start_date_local: "2023-09-21T14:48:46Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 16,
    comment_count: 0,
    athlete_count: 7,
    photo_count: 0,
    map: {
      id: "a9895119643",
      summary_polyline:
        "mp{eGdlv`PSlAqCDKDOV?pBIr@[pAAbBMtCO`@a@\\oEOCHJJl@IyCYe@DaAb@oL@QF{@~@uAlFm@`BS~@Gt@Nr@nBdBfAzAVt@VxCDjAg@xEQx@e@`AmA`BmAbAcExEQt@[f@m@LkB`CgBbFuAhC]b@i@^g@JyFj@kA`@]@k@mA]}AQ{EMw@}AiDk@_BQqB?_DUkBKcD_@uAU_Bk@oByAwCs@yB}@kBcAoE{@iAM_@EmBS}@?SuA}AyEmCAHJRx@x@pAfB`Ah@|AzCv@~@p@pAnA`FN^f@n@n@lBfAjB|@zCf@xC@tCEt@OxAu@fB]V[EaATy@C_@b@s@vCQ`@w@lAu@dB_@bAoAp@Sb@Ir@a@hAWHc@pAaAv@gAP_B|BsA?Sf@k@p@iDhGa@xB?fAPh@b@\\n@|@n@`BPjAKf@L`B~@lEd@hAvA~F`@h@n@`Bl@pAr@hAfB`GVVpAo@dAIXF`@h@t@`CNzBt@nGpCYd@`@d@P|@HxA|AzAn@\\x@In@N|@j@hA^ZxAh@\\Z|@lAf@pAH~ARpA^t@FA~CaExEeHp@i@vAY|@G|JNd@QvAyA`@IvECRaBDiAXoA\\{BBeAMcBqAmCBo@Py@@]y@i@cBKi@QDC?k@Iq@m@iAKs@E]@{@SyAQo@_AgB[WkCtAMCGMUgA?oJEwDGsLPgD?q@RuB?sGR_BCkA?aKHu@PK~AAbDxAi@HaClAc@`@Qp@C\\DZ^f@`@Jb@GvAu@f@a@Xa@Lm@Em@Se@c@YSCmCtAc@`@Ov@Jz@X^RJt@CfAg@x@o@Vc@Js@Eu@a@c@c@Ik@ReC`BQh@@|@JZZZl@BdBu@v@k@Ti@Bs@Ke@Wc@i@KmAh@aBdAWr@A^H\\Tb@RNp@AjAc@lAcAL]Dq@Mo@_@e@i@C{C`B_@`@Gd@D^Th@^Vf@?pAc@hAu@Zk@B{@Mi@a@Y{@?{BpAc@t@Ax@\\|@h@NhBo@bAu@JQFm@Cs@_@k@MiA@KJEbBAPBj@h@dA[bDU`GK`FHLI|B@TYg@iECkAi@mFiAkQY{BSkFY_CK{BHuBCcFIwBFaET_@xAI",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07083667255938, -89.41153080202639],
    end_latlng: [43.071297174319625, -89.41186750307679],
    average_speed: 3.718,
    max_speed: 7.292,
    average_cadence: 83.1,
    has_heartrate: true,
    average_heartrate: 137,
    max_heartrate: 164,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 300.9,
    elev_low: 259.4,
    upload_id: 10605553875,
    upload_id_str: "10605553875",
    external_id: "garmin_ping_295759377879",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 17842.3,
    moving_time: 4695,
    elapsed_time: 4919,
    total_elevation_gain: 88.5,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9889009047,
    start_date: "2023-09-20T19:54:02Z",
    start_date_local: "2023-09-20T14:54:02Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 2,
    kudos_count: 12,
    comment_count: 0,
    athlete_count: 5,
    photo_count: 0,
    map: {
      id: "a9889009047",
      summary_polyline:
        "_`{eGtvu`PrA?tASpHA~@GpSHlGKr@D`BtBt@jAJZYnACt@N`@d@t@Nz@n@t@^pAZ`@Xj@Al@FVjBBb@HrCdARU^u@Z}AIuCDmDXcB\\_DBu@I_CQuAKiCDaAJs@l@{CfBcG\\aAp@yA\\Qb@GdAb@Z\\d@tABr@UbF@vBKdFHt@Rz@d@h@|At@bBdAv@N`AAvGi@v@Fr@TpAv@lDpC|@d@hCbAb@Xj@t@RL\\?zAxA`BvBzD`EtAnAbDxDlAbBh@VzAbBh@hAN~AGh@@Lb@Ll@Kj@Q`@Fh@SnCrCTLfAyBXMf@\\vBbCx@b@|@x@d@TjDjCb@R`@IV]REP?FJXx@Lx@HnACp@St@OvAQl@OtBw@`BK`CQjAH^\\RnA@`@Pz@H~@l@^ERVj@jDLjApB\\h@Vr@j@Zr@^fCChCDjAXzB^fAj@z@N\\Hn@DfBS|BCfADrARxBQnEi@dDmBtAQb@LvAAz@LnAE\\a@bAOx@?V^l@LjAt@zAPh@Mp@IxADt@Hb@L\\t@x@ZbB?p@Fn@JXDf@Ol@e@h@o@\\}@G_@c@[Ig@A{@Y}@gBkAoAMo@Ao@b@g@LEb@gBCImA@e@C[KWpAs@z@Wr@DzCCrAIp@Jx@IXCf@Fx@Cj@Ol@GbAe@dB_@Te@HIFAXzACf@TdBJ`@cAVe@`@U`@Cf@JrAfAn@\\d@HlCCpEDJHH|@FjIG~MIfAWh@g@Ng@BqDEaEFQRCzAM`A]fAqAbCi@d@g@@QrCa@dBA~UAv@Ix@L`ACx@Kt@eBjF]Zc@BqHq@sD_BgAu@oCgCyB}CaBgDyGeTs@}A_@oBi@qBsBiGa@iAcFyKyC{EkA_BkEoF_AuAo@_@aBiC}IkKcByBqC_EmBkDyCmGy@yAeDuHsB}DiCuFyAkDuC}FsFmIwBkCeBaC][m@gA}@mAcBuBg@oAgA_A[c@wA}Bs@aB}@_B_DyISoBm@kCiByMaAsFIcBWcAw@aEs@}ESo@OyAAkBWYOk@K{@u@gE}AiJUeCaAuFk@yEQiA]}@C}Aq@iDKiAQ_AWsB@aCPaBr@mDf@qB\\_@p@mCLq@CSyA?iBM}Bf@HjAYp@Er@BfAHz@DtEAnAQxBDbAAvABjAChDNlDI~@G`DGhAAzDM~@GlECx@Ql@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07052293792367, -89.41059965640306],
    end_latlng: [43.07124176993966, -89.41168611869216],
    average_speed: 3.8,
    max_speed: 6.478,
    average_cadence: 83.2,
    has_heartrate: true,
    average_heartrate: 143.5,
    max_heartrate: 171,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 308.9,
    elev_low: 258.7,
    upload_id: 10599169341,
    upload_id_str: "10599169341",
    external_id: "garmin_ping_295599044744",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 18465.5,
    moving_time: 4412,
    elapsed_time: 6332,
    total_elevation_gain: 141.6,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9882697783,
    start_date: "2023-09-19T20:21:45Z",
    start_date_local: "2023-09-19T15:21:45Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 5,
    kudos_count: 11,
    comment_count: 0,
    athlete_count: 3,
    photo_count: 0,
    map: {
      id: "a9882697783",
      summary_polyline:
        "}qqeG`}paPvN}RzBoDxAgBf@c@f@K~ALh@j@Rl@D~@I`FIr@aAnCs@tAcDjDaA|A@`IGpBMvAmAdFu@fAyCt@sBJkC[k@YuAiBc@sA_@sBEo@NQ\\A~Ar@jB`BrAbAbAh@f@Dv@M~@o@z@wBvAuFPkB?uAGM_@Y[DaBbFoB~Ea@\\YGQO_@eA?gATi@lKiNJk@Gu@]a@k@Ug@Rq@n@{H~LgB~BaA~@kAt@g@Ca@a@Kc@NgAXw@b@u@|GuJrFgHo@n@{BhDmIlL_@^EGpAoAnAaBnKkOvEsHpA_Bv@k@~@CzA\\b@t@Fv@MxGw@bCw@bByCbDqAnBGb@AdB@`GMjBq@hDq@jBe@r@{AXx@eEbBuFj@wCEZMP_BwB}@|C}AvD]\\]CQM]iAAy@`@_AnGeI`CiDBq@CYQ[i@_@QAaAd@w@|@eCvDBLdDxD_DpI]ZSA][]cAA[Jq@t@oAfJuLLm@Eg@M_@g@c@SCe@Js@n@{ChEIf@xCpDL@yC~HWb@a@F_@_@Yw@Ce@Lq@zA{BrHsJR[BUEy@Wc@g@[c@Hq@d@c@h@gCbEDRlCbDLFy@lCwAlD]l@QBg@[Yy@Cu@Le@zBcD|GyIJa@Cs@Q_@a@][K]HeAz@yC|ExCvDJBw@nCcBfE[XQA_@][{@Ai@Fe@jKqNXe@Bu@Ic@W[c@U]@c@Tq@n@yCrErBpC^d@TJs@~BiBvEWTS@e@[Y{@Au@DYx@sAlJyLFWAu@Ui@i@_@QCe@N{A`B{BlDXf@|BpCNJs@dCsAdDO^[^]AOMYm@Ke@FeAz@_BfJwLDWCq@Ug@a@Wg@@g@Xm@p@qCfEgNxFq@sABc@V_BrA_E~AgDx@kAzAqA~@e@~@UbFe@x@]z@{@lAoB|AoBp@SxANb@PLNVp@B~@OhGo@vB{@dBeCvBsArBSnAIrKk@tD}@vCq@p@_Dh@aCHqAQi@U}@u@u@sAg@uBOcBv@@tAn@|@j@dCtBnAj@t@CbAm@~@uBb@qAd@gBRuANoB?wFf@oAHc@Gu@[k@k@Wc@Ji@b@uAhBsHvLs@~@m@f@}@l@e@Fa@QUc@@w@Lw@Tg@jM{QpFkHrDqFgLrPeG|H",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.02228885702789, -89.54961695708334],
    end_latlng: [43.02217352204025, -89.54942291602492],
    average_speed: 4.185,
    max_speed: 7.004,
    average_cadence: 85.9,
    has_heartrate: true,
    average_heartrate: 148,
    max_heartrate: 178,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 343.5,
    elev_low: 320.2,
    upload_id: 10592584161,
    upload_id_str: "10592584161",
    external_id: "garmin_ping_295438169054",
    from_accepted_tag: false,
    pr_count: 3,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 16071,
    moving_time: 4188,
    elapsed_time: 4359,
    total_elevation_gain: 53.2,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9875994535,
    start_date: "2023-09-18T20:16:10Z",
    start_date_local: "2023-09-18T15:16:10Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 5,
    kudos_count: 10,
    comment_count: 0,
    athlete_count: 8,
    photo_count: 0,
    map: {
      id: "a9875994535",
      summary_polyline:
        "orreGteh`Pp@e@L[KuA@iCMsAMo@Yy@k@_CMcAOi@]c@gAu@]c@{ByBAIXwAFs@@kACsAEIyAa@e@g@eDwH]Oy@j@q@A{CkA}@QyCSg@M[We@u@[kBgA]m@{@[_@uAaAO[My@Co@@w@Qi@q@w@[i@[iA_A_@Gc@Oq@qAe@S[Sq@I_AA}BD}Ax@_G`@yBzBoF`CyEfFyLrE_K|B}EhDkIb@u@lAsAdAeB|@uBzCgF`BaDTk@RcAT}BW`C[pAWn@mA~BkD|F_A~BiAfB}AhBYj@qA|CyEfK}IjSqAnC}AtDeCrF]bAWxAAP\\Ed@?l@j@Vx@VHj@Mj@Lb@XTf@Hj@RZ\\?f@K`@Rv@rA|@z@x@pAl@j@dArA|BvDdAhAb@n@rDnEr@Xl@l@f@p@tA`@`@Ab@\\fAJzAG`DuAt@n@r@bAb@R~@LZ\\Rb@bADxAMRc@@eAFy@TQ`@@VUVa@FARYE}@FeAEmBBcAHM^ErENTLl@xAXb@zAvAbBrA^`@bC`Dr@nAhAzAXd@n@vAd@l@h@ZsAmAm@oA{BAaB`@ETIbCFhITLb@HPPRGVHJp@TZnAf@tAdAd@Rp@jAX`@Fz@EV@NPr@Dt@ItA?rBGb@IF[Q[Jo@YEm@Ik@By@Qs@YIaAL}@MMSIy@Cw@BkBBa@Ti@E[Jo@E]_@aAOm@}CEuBMyDI_Le@wBQ]_@Eu@B_CCmA?aD_@cAKu@EIQ@Wn@uADUHKr@S`@Gv@Il@Bx@Av@Sb@QNs@R{Az@_Bj@_AHc@Ii@m@gD}HUMs@`@g@IeBe@{DuBc@?u@h@SX?LDLrErDbA`AjHrHjBzBVb@\\~@h@h@QUnGFlDPnAK?GuAJ{DOyFCu@m@mBeCsDyDmDqDiCaCdJzIhIrJ|AxAt@~AV|ALVf@f@r@bAr@ThBJ^TN`@M|NKtAQbBWjAqBvEq@zBiA`BGf@AhAIh@QFm@EiCBgAZgBH?wCFgBPaAn@_B\\e@\\WJUISAe@FcCFWXW`@UPw@z@s@b@y@b@Sp@E`@QX[NPTjBLjBHn@^j@DZGVeAjB?^TdACXm@zAcA`BQdCGN_DCe@@iAVqABOGEi@@q@FqBFu@ZaA`@eAr@s@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.027081713080406, -89.34330211021006],
    end_latlng: [43.026258861646056, -89.34361827559769],
    average_speed: 3.837,
    max_speed: 6.425,
    average_cadence: 83.4,
    has_heartrate: true,
    average_heartrate: 150.8,
    max_heartrate: 178,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 271.1,
    elev_low: 257.7,
    upload_id: 10585566686,
    upload_id_str: "10585566686",
    external_id: "garmin_ping_295267690382",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 21150.5,
    moving_time: 4866,
    elapsed_time: 4934,
    total_elevation_gain: 36,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9868835231,
    start_date: "2023-09-17T14:35:52Z",
    start_date_local: "2023-09-17T09:35:52Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 3,
    kudos_count: 19,
    comment_count: 0,
    athlete_count: 16,
    photo_count: 0,
    map: {
      id: "a9868835231",
      summary_polyline:
        "gl|eGd_l_PiBi@SOYe@Us@KiCAeCBgDHq@FkCHiAFiB?kABe@\\gEHaBHs@BcARgBReDRkB`@{Er@iJBq@RkCr@mH\\mHFw@^aD^kEFgA`@oFJkBRyBJcCf@yDVsC~BmP`@wBv@{FtAgIVyB~@gGn@yDTeAX}BxAyJTqBz@{EVoB~@kFb@uDb@qC`@}Bb@{CVmAh@cDl@gFl@oEpAeId@oC~AgKVyARgBR_AJgAdAkHrA{HTsBTiAJcAZoAn@iEXeBxAuKTmAf@mDD{@dAcGVwBPgA\\kB~AiJXmBf@wC`@}CnBcMh@yEb@qEL_CJqCFu@@mALyDB}JE}BGsFIiAS{G_@oHAm@IgBESIw@k@uH[}BEaAg@mEMaBUiBKiAk@aFGiASkBIgAIo@QiCKi@Gs@Mq@KiAMgAAkCC_@DiDNuCVqBb@iCh@yB\\eA~AwDjC_HnAaDr@sBlCeHX{@Le@\\q@t@wBbAgCp@}AdA_DRe@`AyCbAaCp@oAx@iBnB}FdEeK`@oAT_Al@uBp@iDVqBh@aGd@wGh@oGNqChAyMb@wCt@sDXgAj@gBbH}PfAwCpAaDp@wAjB}E\\o@d@mAdBgEl@sA~AgEh@mA`BgEpA{Cn@kBhAmCTo@bC}Fl@aBjBkEfCsGhCeGf@gAlE}KPo@Z{@bAiDbA}Dd@eCp@wEn@{FP}BDwAJeABoCHoC@}EYsHCiBMeDS_DOkEMiEIaACgAi@}KAo@KoBCqAC[GiCGw@AeAi@cK@y@GgAKoAE_BUqEEwAG_@OkAMmBI_@Kw@Cw@Q{BYgBu@wFYwAIi@Kg@q@}CSc@WkA]mBQu@o@sCe@gBIk@]kAYuAiAoEQkAm@qCe@_Bg@_CQg@QkAWsAUu@Ki@Og@QeASk@]}AUuA]_AIa@Us@Ec@Oe@_@}B_@}Ae@}AUcAG][mAE_@a@yAe@aCo@}Bi@wCi@mBUkAKq@Yy@U_BI_@Yw@I_@Im@e@yAe@eCOcA[aBY{@o@}B_@kB}@oDg@}Aa@sBi@mBa@cCwB{I]gAiA{E{AkHwAuGwBkK[iAEWR^bAnDp@|C`@|Aj@fCVtApAbG\\nAThA~@rDxBdKtFlVj@xBf@fCnAhFTpA`@rAf@`C`@vAh@pC`AhEz@lDb@~An@|C~BvJV|A|@fDRrAf@pBXxADFZ|A",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.076174603775144, -89.19795613735914],
    end_latlng: [43.04711990989745, -89.01258054189384],
    average_speed: 4.347,
    max_speed: 5.56,
    average_cadence: 84.6,
    has_heartrate: true,
    average_heartrate: 156.9,
    max_heartrate: 180,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 275.6,
    elev_low: 253.9,
    upload_id: 10578049458,
    upload_id_str: "10578049458",
    external_id: "garmin_ping_295062013102",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Morning Run",
    distance: 19348.7,
    moving_time: 4619,
    elapsed_time: 6197,
    total_elevation_gain: 60.6,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9860838840,
    start_date: "2023-09-16T12:48:50Z",
    start_date_local: "2023-09-16T07:48:50Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 5,
    kudos_count: 13,
    comment_count: 0,
    athlete_count: 4,
    photo_count: 0,
    map: {
      id: "a9860838840",
      summary_polyline:
        "{xzeGdtv`P~CAz@wCrDwEc@pAyBvCkAx@B|@cCEyJp@uE_@kKLk@NMVCdHq@hAcEWCPx@M_DQaBj@sCHCtTWhKLxISlHiDrAiGJq@a@gEDi@z@_AZiAnAq@jA_CvGs@lAw@d@{JdBa@Ke@gBMkAUsFsCmH}@gQ}BuIn@hA~AtGThB`@dMpCzH\\~Gt@~BVLpI_BxAs@tB}D|AqEfBsBpCyAxDChCZxCrAy@DyChBOn@Hr@r@z@dBc@`BmAJ_AYeA{@YmDrBO^@v@Ld@j@`@r@IlCeBVcAWeAgAW_DnBOn@Bt@l@|@nASxByAR{@Gu@Q_@q@_@oDrBSj@?t@\\t@n@RjDmBRgAIs@e@i@q@AgDxBIbAPr@j@`@j@C`DwBHq@SgA_@[g@?kD|BIr@Ln@d@h@p@@~CuBH_AU}@a@[g@@gDxBIbAPn@^^n@@~CoBNq@SsAe@[e@BgDxBGlA\\v@vABhCaBJmAYcAeAQeD~BGt@Lp@`@b@z@A~C_CHoA_@s@aACcDxBKr@Ft@\\f@r@DdDyBNiAKq@u@e@aALuBjAWf@Ir@VpAdA\\dDiB\\s@G{@g@{@m@KgDpBQx@Dr@^n@d@HfDeBX_AAu@a@s@a@IiDhBWj@@|@\\r@n@P~CgBT}@I_A_As@mDpBSr@?j@Xr@r@T`D_B`@gAAi@e@y@i@I_D~AYh@A`Ad@z@d@JhDgBP}@Ew@Wi@i@MqDpBQr@Ft@\\h@h@HfDcBXw@GcAYe@s@GkDpBOt@Fv@f@r@h@B`DqBPwAQq@eAWaDlBS|@Hv@^d@p@FbDyBL}@Is@m@m@c@@{CjBSl@Bz@`@t@h@FnDqBNoAMq@y@c@qDpBUl@LnAh@f@h@EvCiBRi@OyAg@a@e@?kDbCArAl@x@p@AlAm@fAu@Xw@MoA]_@q@ByBlAo@f@Kd@@h@Vp@n@TbDaB^o@Hu@Qo@m@_@sD`B]d@Ex@b@hAf@LhDcB^qAKu@[e@OuAtBB^t@ZFtAq@lI[p@_@~CV~EUDgA{Eao@BaKdGOh@ThCc@fHP|IW\\c@BuCrFsH`A_BHg@rCoDCkI}ELRx@bDvFNj@qIbLc@dAg@^@x@Yx@I`FWAMgAUC",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07039117440581, -89.41455532796681],
    end_latlng: [43.070268128067255, -89.41496226936579],
    average_speed: 4.189,
    max_speed: 6.523,
    average_cadence: 85.5,
    has_heartrate: true,
    average_heartrate: 152.8,
    max_heartrate: 188,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 281.4,
    elev_low: 259.5,
    upload_id: 10569651280,
    upload_id_str: "10569651280",
    external_id: "garmin_ping_294881882346",
    from_accepted_tag: false,
    pr_count: 1,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 16217.2,
    moving_time: 4254,
    elapsed_time: 4623,
    total_elevation_gain: 98,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9856276102,
    start_date: "2023-09-15T19:50:39Z",
    start_date_local: "2023-09-15T14:50:39Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 9,
    comment_count: 2,
    athlete_count: 3,
    photo_count: 0,
    map: {
      id: "a9856276102",
      summary_polyline:
        "}q{eGxnv`PoCAQBCJI~@L`AEfBa@p@CTBp@Sr@LnAMf@a@^sC?g@IMB?LDBx@IuCOi@@a@Vq@NeLAYFm@j@_@z@i@rCs@lB[pAInAHl@tCdCh@~@ZzAP~CCx@]nDOz@Sh@mBvCmB~AuBzBYh@Ut@Wj@}@ZeBxBcB~EcB|Cu@d@k@N{D^_Dp@][CW_@q@I[SuEUiBcAyCq@wAMu@SuB@uB]{B@qBMkAQm@KkAoAyDm@{@cAsCo@cAY{@w@yDUk@k@o@Mi@Bk@Gi@YgA?QmAyAuBgA_BgAS@@N~@x@nAdB|@h@h@l@v@dBlAbBXh@Rn@r@fDBLE^T`CLdCHpEAhFQ|FIr@gAbEeAbBe@fAg@x@Mp@g@d@a@HQRWl@?f@Ur@m@f@_@`A_@b@qAT]r@cAlAuABOPUf@o@x@sAdCw@hAYv@WfBFbBr@j@r@z@z@bCBr@G`@?~@bAdFr@lBbAbEv@pAX|@z@pBdA~A`@pALbAT~@ZX`Ai@rAE^BTVT\\j@|Bl@dHTxAl@@dAU`@BnAx@l@A`@V`B`Bv@R^ZBf@Et@Jn@d@`AlC~AzAfBVf@VjCPhATl@RBNSbAeBrBsCSyA?u@DY`CwEVu@Lo@KgCKu@D[h@e@jA]xAQbCGdA]h@q@Xw@Da@Eo@GOWa@qBiByBaE_@cA[wBM_B@]hBSdDcA^_@Do@Iu@C}DDqICkGIqC?m@Hu@NoJDcAEeKB{AAoC@s@FSt@UbEBaBPdAT`@TN?t@rDOBuEm@t@pCLItBwFH@RrAN|@gFe@R~@b@pAF@pBwFFIHHHv@ZhACPqEq@QBt@pCJCnByFHEFL^jCCBgFi@h@tBP\\bCgGZKYKm@HgCxAg@n@Il@Hp@Tn@b@Vb@BpD{BZw@Ak@Mm@c@i@u@GiCtAi@d@Qb@Cp@Ll@`@j@r@Lj@S~ByA^m@Dw@Ms@_@g@a@Ie@H_DzBVEdDmBsBmAxFBRLPl@J?\\Ef@[j@I`EK|H?VCQGPIxEADOW{DEoBy@uICqAk@wIg@_GGuASiCOm@IgCNkFGaDLwBDgCNYtCOd@UJ_AIy@Bk@vA?`BKPMO{FLkARs@LqBJa@bCQd@HnA~Ap@fBfAbClDzGRp@v@|E?^e@P_E?",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07133019901812, -89.41081691533327],
    end_latlng: [43.07127538137138, -89.41194646060467],
    average_speed: 3.812,
    max_speed: 7.306,
    average_cadence: 83.3,
    has_heartrate: true,
    average_heartrate: 139.8,
    max_heartrate: 168,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 301,
    elev_low: 259.4,
    upload_id: 10564848739,
    upload_id_str: "10564848739",
    external_id: "garmin_ping_294767268722",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Afternoon Run",
    distance: 16848.8,
    moving_time: 4238,
    elapsed_time: 4319,
    total_elevation_gain: 48.6,
    type: "Run",
    sport_type: "Run",
    workout_type: null,
    id: 9850612337,
    start_date: "2023-09-14T20:35:42Z",
    start_date_local: "2023-09-14T15:35:42Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 2,
    kudos_count: 10,
    comment_count: 0,
    athlete_count: 7,
    photo_count: 0,
    map: {
      id: "a9850612337",
      summary_polyline:
        "yqreGneh`PZWJe@IoABoAAwAYkBo@sBs@_DWi@eAs@}AiBgAcAYG_@]wCqDuF_GsHcHaBsAWm@QsAMSgA[_@o@a@c@}AmAY}ADoAQs@ZcEZqBCcAMKi@AuAe@s@eAYWIWSeAO]]U_A]GK@c@Lo@l@gENu@Xw@nHsPvEsJpBuEvBkFjEsJf@cA`BqBp@iAx@mBr@uAjEcIb@iA`@uBYbBs@lByAjCYr@sBlDk@tA}@dB[f@wAxAa@p@kGhNgJhTuIjRUn@Qv@K`AfABXNPNNt@HLPHn@Oh@Jl@h@Nt@N`@ZJj@S\\DvAzBb@b@v@fAdBjB|@tAjAxB~AfBrDrEjAp@lAtAr@TJJ|@D\\XvAJhAGd@K|BcAh@B^RtA|Ax@\\\\z@h@^D^]|A?PB|IPbAb@PlETdVx@f@ENTFf@X\\p@NVZlAz@XHXZTj@j@l@Db@Ct@D`@Rn@?l@Mz@@lCE`@IDg@KQFo@[McBBm@Og@QYuADy@MKe@Gw@@eAHiBR]BMGy@Ba@Ii@o@uAm@JeDUsOg@gEWu@OW]Eu@@kBC{GBy@Ci@u@sAeA]qCkBaChAe@LkA@u@EkAg@]DYW_@I_@Wg@o@o@e@u@[_DeEg@s@_@WM?]n@k@tBEr@L`AS`DKx@YfAM`As@xBAJFJbDpCfH|GnFlGjDvDx@rARt@Jz@Tf@h@h@^n@`@XvBT`@RHLJd@@fIOnD]dDMn@qA|Cw@nCg@hA{@rAKj@A|@KhAHv@ElCD~AAvAi@hEEr@FrCCZQJo@CaIi@w@c@_@_@_@y@qA{AMHcBjDUlABNz@MZJHXGnADp@Z^lDHb@Mf@]LCXPl@j@h@V~An@^^Vv@RTj@hAh@j@Xn@f@p@t@nBjAz@`@v@h@nA?d@Kd@K~AJj@^Z^f@d@BDLChGFlHAfJBpHEbJFn@dAdBjBtDdJL|@Oh@q@Nq@H_B_@eBCaA@uBZcDCu@W{@]u@_@_@wAy@U_@Ke@@aAj@uKFcJAsAWaAo@sA}A{CaAqAM[Eu@Dy@Gm@aA_ByAkAa@eBi@q@s@gCO}@OsB[gAi@o@w@Sg@?mA\\g@?_@[Qm@FaAf@eCTsB@q@IiA]kCAkAE}@Fo@",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.02703737281263, -89.34314880520105],
    end_latlng: [43.027051789686084, -89.34322885237634],
    average_speed: 3.976,
    max_speed: 4.863,
    average_cadence: 83.4,
    has_heartrate: true,
    average_heartrate: 142.2,
    max_heartrate: 156,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 267.3,
    elev_low: 257.5,
    upload_id: 10558901940,
    upload_id_str: "10558901940",
    external_id: "garmin_ping_294613541143",
    from_accepted_tag: false,
    pr_count: 2,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "“Stay away until Thursday” pt 2",
    distance: 13809.8,
    moving_time: 3675,
    elapsed_time: 3780,
    total_elevation_gain: 61.6,
    type: "Run",
    sport_type: "Run",
    workout_type: 0,
    id: 9841785329,
    start_date: "2023-09-13T14:03:46Z",
    start_date_local: "2023-09-13T09:03:46Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 13,
    comment_count: 0,
    athlete_count: 2,
    photo_count: 0,
    map: {
      id: "a9841785329",
      summary_polyline:
        "q_{eGfzu`Pv@aAPe@ZUz@[lDKZHtHAlAFp@C`JA~CG~CJZHf@f@Zb@RbAl@xBD|Aj@fAPr@Hh@^Z`@pAHL\\b@JVDbARNfAI`AJ|BbAL@VOJKNYRs@F[Ds@KcCDmBFc@l@aBXcDIaCe@eCK{@C}A@u@JaAX{@l@wC`AgCZiAz@{Bb@s@^SVBp@`@X^`@z@Ll@@v@QbGBz@MxDDrALv@d@x@b@ZpCzAd@RRB`A@`Gc@lAB`ARl@X`Az@tDlCbAf@h@Np@Zr@d@r@|@V?]AAFBxAAhIGbEIxCFr@\\fCb@pB\\nB`@jDT`ADbBCx@BrADjAZ`BNb@Tj@|@pAZRd@An@I`Bq@vA[j@UjABd@N^Xp@lAHx@LCBG@PHH\\JxB|B~@p@HLXn@Xf@RzAB|@CF@f@Pf@^\\fAh@rA|@hAfAJBh@APFh@b@VNhBzB`@X`@b@Tj@Bd@hBF`BNl@M|@c@t@q@Ne@HaB^qBTy@`@]f@GlATv@Vf@Zb@\\Vd@JRJp@Nt@Dr@EpADjAXbBNj@Bd@FXPj@`@n@Nj@LtAG|@Mt@IpADj@AxAF~@Hb@@b@IxBAv@GX[bCY`@c@\\i@X]\\GZJ|@Cp@Dh@Pp@@j@CN[dA{@zBc@Zm@JY?_@PQVBh@Hp@^dB@h@E\\a@^a@FgAM_@Oo@x@o@dASr@Iz@GxBJxCFx@DhAKx@OtBEdASh@a@PmATo@TqANoC@aCKgGDq@Cm@PoAjBUl@Yf@oAxA}@`B}@fA[~@W|BC|@?~AFdECrADnBGbGEJiA?WOY}@s@mCyA}D_@u@i@}A_BaDu@gB}BaEaCsDmB{Bq@aAgBuBMUgAy@i@cAg@s@_DcE{DuEo@_As@{@oAmBs@y@yEaJ]k@e@mAyAcDaAcBo@sA}AoD[c@_@aAwC_Gc@oAi@cAYs@cBeD{@wAeBaCMWaBuBiAaBwAgBeCqDeBcCa@c@M_@Ye@g@k@iEcGOc@BMAGk@q@_@s@_@iAwA}E]}Bo@gDk@eEu@uEw@eEIu@Oa@Au@s@mDI_AWeBI[a@kCCEw@O{FNeANwAj@y@@oAO_A_@_@WQoA",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07136691175401, -89.4104459322989],
    end_latlng: [43.07051363401115, -89.4104681443423],
    average_speed: 3.758,
    max_speed: 4.78,
    average_cadence: 83.5,
    has_heartrate: true,
    average_heartrate: 157.9,
    max_heartrate: 180,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 297.2,
    elev_low: 259.1,
    upload_id: 10549707133,
    upload_id_str: "10549707133",
    external_id: "garmin_ping_294401789189",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "“Stay away until Thursday”",
    distance: 9668.6,
    moving_time: 2496,
    elapsed_time: 2511,
    total_elevation_gain: 36.7,
    type: "Run",
    sport_type: "Run",
    workout_type: 0,
    id: 9835177964,
    start_date: "2023-09-12T15:07:15Z",
    start_date_local: "2023-09-12T10:07:15Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 8,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9835177964",
      summary_polyline:
        "kwzeG|hv`PFN`@hCFPh@VHLNl@F~@Ln@J|@`@lBH|@^lBLt@HfAXrA?RP|@Hv@Rz@RxBPnAj@tCt@rETxAH~@b@`BFd@Np@Vh@Tt@Rh@^l@h@fANDDCFBd@lAX`@h@jB`@b@b@\\f@x@^\\X^Xx@dAxAb@`@d@Z|@|ANRJF^^Nd@v@bA^h@Vn@n@r@~CrEx@vAv@~A`@b@^vATf@dAdBZj@HVxAvCl@z@Td@Rn@|@fB\\hAR`@`@d@Zv@Xh@BHp@vAPh@LPp@vAHJ`ArBJb@^r@r@dAj@pAZh@l@x@r@hA@HT`@rBpCn@p@v@dAl@p@X`@z@t@\\\\FL\\`@XT\\\\Zh@f@j@L`@X^x@t@pAxBp@p@^p@h@ZjAhAhAzB~AlCb@z@\\h@lA|BN`@RZd@fArArDf@zAn@~BJR`@dBf@bBJj@Vj@n@bB`BvFV~@j@bBl@jB^~APb@T^VJAGs@eAq@}Ay@_C]iA_@_AeAuD[y@s@qB[u@S}@Mu@]mAq@uB_AaCq@wB[c@y@uBQk@_AqBq@qAs@eAc@e@Wq@gBkCUe@i@g@[k@s@i@i@q@]]i@s@Ym@a@_@o@g@Sk@aAoAk@i@_BgBgAgAMYa@i@oBiCIY[a@a@[eAgBu@mAk@gAiAgB]y@sAcC{AaDe@w@u@mB[k@w@_BUo@Ye@i@eAq@eAY_Ac@g@q@{B[g@u@gBa@q@Wo@q@iA]aA}@{Aa@y@yA}BYk@_@_@g@u@{BoCa@]c@m@c@]Yc@_@_@y@{A]c@_@s@m@{@M_@Yc@_@Y]c@mAaBk@eAECi@q@Wg@K_@k@y@e@_Bc@kAeAsD_@aDQmAMk@g@mDS_C}@gF_@aB[u@Ew@UaBSiBAq@UsAWu@a@wBG_@CCK?c@SOk@Kw@YoAQeA",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.07048287242651, -89.41037259064615],
    end_latlng: [43.0704212654382, -89.41046847961843],
    average_speed: 3.874,
    max_speed: 4.733,
    average_cadence: 83.1,
    has_heartrate: true,
    average_heartrate: 146.5,
    max_heartrate: 165,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 299.9,
    elev_low: 263.1,
    upload_id: 10542772109,
    upload_id_str: "10542772109",
    external_id: "garmin_ping_294239018068",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 106301232, resource_state: 1 },
    name: "Not quite back yet",
    distance: 9666.1,
    moving_time: 2458,
    elapsed_time: 2510,
    total_elevation_gain: 28.6,
    type: "Run",
    sport_type: "Run",
    workout_type: 0,
    id: 9828449204,
    start_date: "2023-09-11T14:08:24Z",
    start_date_local: "2023-09-11T09:08:24Z",
    timezone: "(GMT-06:00) America/Chicago",
    utc_offset: -18000,
    location_city: null,
    location_state: null,
    location_country: "United States",
    achievement_count: 0,
    kudos_count: 11,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a9828449204",
      summary_polyline:
        "i~zeGxuu`PNATDnAMd@@jGOZB`FFjBAlBE~AAvB@t@DdA@j@CjA?zAFb@PdClDHj@O`AEn@p@pAl@hBZ\\XdAFNZ^Rf@Dx@JHbAMd@Dn@PtAt@ZHVM`@{@V_ABu@Eu@CkADcDHm@v@eCDw@EaAe@gFK{AD{AZsBVyAlDwK^y@RYXGHGRq@\\i@z@}@tAmBVYp@e@xAoAp@_@h@Ol@Wd@W`A_@t@AhBUdDi@lAMlAI\\IdBORGZ]Vo@NMD?`@PtAhAzCzB|B|ApHtFt@`@nA|@n@h@zAr@z@Vf@Fb@NDF@f@?pABl@@vCElCApIA\\AhCKrEDbKMdIF~AInC?vAQf@a@Vg@b@[JsAi@_@Ie@Pw@p@mAh@QNwA|@[T}ArBg@z@a@Rc@O_AyAcAy@Um@m@e@[k@Yq@EwA?s@CWDiDCy@F}DAs@JeFSo@a@_@k@]aA]cAY_CyAeDyBs@a@u@KeA?oALk@LaBNq@?g@Eq@OaBgAuAi@_@[_@u@CUAy@HiBCmCFaBCsAF_ACw@Jq@U{@Uk@g@g@KOk@e@]P_@`@[t@kAdEqA`EYjBOdBD~BJhAb@rCBdBSnBGN_@p@Or@MzBFtCAhAMl@KVg@v@QLKAqB{@c@My@G_ADOOAm@Ks@YUi@qA_AsAOu@Wk@[aAFw@Jw@@_@Qa@yAuA[g@SMgAO_C?s@DaAGoAFOAyADq@Fu@Ci@BmEA_BDoBIy@DGCcA?]@MAe@BuACkBBWQ_AESB",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: false,
    visibility: "everyone",
    flagged: false,
    gear_id: null,
    start_latlng: [43.070469880476594, -89.41045800223947],
    end_latlng: [43.070545652881265, -89.41056462004781],
    average_speed: 3.933,
    max_speed: 6.284,
    average_cadence: 83.3,
    has_heartrate: true,
    average_heartrate: 141.6,
    max_heartrate: 154,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 267.9,
    elev_low: 258.8,
    upload_id: 10535705009,
    upload_id_str: "10535705009",
    external_id: "garmin_ping_294070196308",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
];
